{{- if and .Values.kargo.projectConfig .Values.kargo.project.enabled }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ .Values.kargo.project.name }}
  namespace: {{ .Values.kargo.project.name }}
spec:
  promotionPolicies:
    {{- range .Values.kargo.apps }}
    {{- if and .enabled (eq $.Values.global.argoApp.environment "stage") }}
    - stage: {{ .name }}-stage
      autoPromotionEnabled: true
    {{- end }}
    {{- if and .enabled (eq $.Values.global.argoApp.environment "prod") }}
    - stage: {{ .name }}-prod
      autoPromotionEnabled: false
    {{- end }}
    {{- end }}
{{- end }}

