{{- if .Values.kargo.project.enabled }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: create-git-tag
  namespace: {{ .Values.kargo.project.name }}
spec:
  steps:

  # Step: Clone the repository
  - uses: git-clone
    config:
      repoURL: ${{ "{{" }} vars.repoURL {{ "}}" }}
      checkout:
      - commit: ${{ "{{" }} commitFrom(vars.repoURL).ID {{ "}}" }}
        path: ./src

  # Step: Parse the version
  - uses: yaml-parse
    as: parse-version
    config:
      path: ./src/helm/${{ "{{" }} vars.appName {{ "}}" }}/Chart.yaml
      outputs:
      - name: depVersion
        fromExpression: "dependencies[0].version"
      - name: chartVersion
        fromExpression: version

  # Step: Compose the tag name
  - uses: compose-output
    as: tag-info
    config:
      tagName: ${{ "{{" }} vars.appName {{ "}}" }}-${{ "{{" }} task.outputs['parse-version'].depVersion {{ "}}" }}
  # Step: Create the tag
  - uses: http
    config:
      url: ${{ "{{" }} vars.gitApiUrl {{ "}}" }}/repos/trawler/kargo-demo/git/refs
      method: POST
      headers:
      - name: Authorization
        value: Bearer ${{ "{{" }} vars.gitApiToken {{ "}}" }}
      - name: Accept
        value: application/vnd.github.v3+json
      body: |
        ${{ "{{" }} quote({
          "ref": "refs/tags/" + task.outputs['tag-info'].tagName,
          "sha": commitFrom(vars.repoURL).ID
        }) {{ "}}" }}
{{- end }}
