{{- if and .Values.kargo.stages.enabled .Values.kargo.project.enabled }}
{{- range .Values.kargo.apps }}
{{- if and .enabled (eq $.Values.global.argoApp.environment "stage") }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}-stage
  namespace: {{ $.Values.kargo.project.name }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .name }}-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: appName
          value: {{ .name }}
        - name: repoURL
          value: {{ $.Values.kargo.warehouse.repoURL }}
        - name: gitApiUrl
          value: {{ $.Values.kargo.gitApi.url }}
        - name: gitApiToken
          value: "${{ "{{" }} secrets.git-api-token {{ "}}" }}"
      steps:
        - task:
            name: create-git-tag
            kind: PromotionTask
{{- end }}
{{- if and .enabled (eq $.Values.global.argoApp.environment "prod") }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}-prod
  namespace: {{ $.Values.kargo.project.name }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .name }}-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: appName
          value: {{ .name }}
        - name: repoURL
          value: {{ $.Values.kargo.warehouse.repoURL }}
        - name: applicationsetFiles
          value: {{ .applicationsetFiles | toJson }}
      steps:
        - task:
            name: update-applicationset
            kind: PromotionTask
{{- end }}
{{- end }}
{{- end }}


