{{- if .Values.kargo.project.enabled }}
{{- range .Values.kargo.apps }}
{{- if and .enabled (eq $.Values.global.argoApp.environment "stage") }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}-stage
  namespace: {{ $.Values.kargo.project.name }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .name }}-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: appName
          value: {{ .name }}
        - name: repoURL
          value: {{ $.Values.kargo.warehouse.repoURL }}
        - name: gitApiUrl
          value: {{ $.Values.kargo.gitApi.url }}
        - name: gitApiToken
          value: "${{ "{{" }} secret('git-api-token').password {{ "}}" }}"
        - name: gitRepoOwner
          value: {{ $.Values.kargo.gitApi.repoOwner }}
        - name: gitRepoName
          value: {{ $.Values.kargo.gitApi.repoName }}
      steps:
        - task:
            name: create-git-tag
            kind: PromotionTask
{{- end }}
{{- if and .enabled (eq $.Values.global.argoApp.environment "prod") }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}-prod
  namespace: {{ $.Values.kargo.project.name }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .name }}-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: appName
          value: {{ .name }}
        - name: repoURL
          value: {{ $.Values.kargo.warehouse.repoURL }}
        - name: gitApiUrl
          value: {{ $.Values.kargo.gitApi.url }}
        - name: gitApiToken
          value: "${{ "{{" }} secret('git-api-token').password {{ "}}" }}"
        - name: gitRepoOwner
          value: {{ $.Values.kargo.gitApi.repoOwner }}
        - name: gitRepoName
          value: {{ $.Values.kargo.gitApi.repoName }}
      steps:
        {{- $appName := .name }}
        {{- $defaultPromotionTasks := $.Values.kargo.apps._default.promotionTasks | default (list "update-applicationset") }}
        {{- $promotionTasks := .promotionTasks | default $defaultPromotionTasks }}
        {{- range $promotionTasks }}
        {{- $taskName := "" }}
        {{- if typeIs "string" . }}
        {{- $taskName = . }}
        {{- else }}
        {{- $taskName = .task }}
        {{- end }}
        - task:
            name: {{ $taskName }}
            kind: PromotionTask
        {{- end }}
{{- end }}
{{- end }}
{{- end }}


