apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-applicationsets-management-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/trawler/kargo-demo.git
    path: helm/argo-cd-applicationsets
    targetRevision: main
    helm:
      values: |
        global:
          argoApp:
            environment: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
