global:
  argoApp:
    environment: stage

postgresqlClusters:
  enabled: true

# App revisions for stage environment (mostly main/head)
apps:
  cert-manager:
    revision: main
  argo-cd-applicationsets:
    revision: main
  kargo:
    revision: main
