global:
  argoApp:
    environment: prod

postgresqlClusters:
  enabled: true

# Control cluster apps for prod environment
controlApps:
  cert-manager:
    appRevision: 
  argo-cd-applicationsets:
    appRevision: main
  kargo:
    appRevision: main

# Workload cluster apps for prod environment
workloadApps:
  cert-manager:
    appRevision: cert-manager-1.17.1
