global:
  argoApp:
    environment: prod

postgresqlClusters:
  enabled: true

# Control cluster apps for prod environment
controlApps:
  - appName: cert-manager
    appRevision: cert-manager-1.17.1
  - appName: argo-cd-applicationsets
    appRevision: main
  - appName: kargo
    appRevision: main

# Workload cluster apps for prod environment
workloadApps:
  - appName: cert-manager
    appRevision: cert-manager-1.17.1
